import 'package:lizunemu/core/lore/models/lore_param.dart';

/// Versioned maximal NSFW ontology modules. Fields are sparse — null/absent is fine.
class LoreOntology {
  static const int version = 3;

  static const String moduleIdentity = 'identity';
  static const String modulePsyche = 'psyche';
  static const String moduleRelationship = 'relationship';
  static const String moduleClothing = 'clothing';
  static const String moduleLocation = 'location';
  static const String moduleBody = 'body';
  static const String moduleFace = 'face';
  static const String moduleFluids = 'fluids';
  static const String moduleFertility = 'fertility';
  static const String moduleRisk = 'risk';
  static const String moduleToys = 'toys';
  static const String moduleKink = 'kink';
  static const String moduleCustom = 'custom';

  /// Explicit modules hidden under SFW contentLevel until reveal.
  static const Set<String> explicitModules = {
    moduleBody,
    moduleFace,
    moduleFluids,
    moduleFertility,
    moduleRisk,
    moduleToys,
    moduleKink,
  };

  static const List<String> allModules = [
    moduleIdentity,
    modulePsyche,
    moduleRelationship,
    moduleClothing,
    moduleLocation,
    moduleBody,
    moduleFace,
    moduleFluids,
    moduleFertility,
    moduleRisk,
    moduleToys,
    moduleKink,
    moduleCustom,
  ];

  /// Starter defs the LLM / editor can fill. Custom keys still allowed.
  static List<LoreParam> starterParams({bool includeExplicit = true}) {
    final list = <LoreParam>[
      const LoreParam(
        key: 'role',
        module: moduleIdentity,
        label: 'Role',
        type: LoreParamType.enumeration,
        enumOptions: [
          'heroine',
          'rival',
          'listener_insert',
          'side',
          'narrator',
          'other',
        ],
      ),
      const LoreParam(
        key: 'personality',
        module: modulePsyche,
        label: 'Personality',
        type: LoreParamType.text,
      ),
      const LoreParam(
        key: 'arousal',
        module: modulePsyche,
        label: 'Arousal',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
        hudPinned: true,
        accentHex: '#E91E63',
      ),
      const LoreParam(
        key: 'horny',
        module: modulePsyche,
        label: 'Horny',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
        hudPinned: true,
        accentHex: '#FF4081',
      ),
      const LoreParam(
        key: 'pleasure',
        module: modulePsyche,
        label: 'Pleasure',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
        hudPinned: true,
        accentHex: '#F06292',
      ),
      const LoreParam(
        key: 'pain',
        module: modulePsyche,
        label: 'Pain',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
        accentHex: '#EF5350',
      ),
      const LoreParam(
        key: 'shame',
        module: modulePsyche,
        label: 'Shame',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
        accentHex: '#AB47BC',
      ),
      const LoreParam(
        key: 'fear',
        module: modulePsyche,
        label: 'Fear',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      const LoreParam(
        key: 'trust',
        module: moduleRelationship,
        label: 'Trust',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      const LoreParam(
        key: 'obedience',
        module: modulePsyche,
        label: 'Obedience',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      const LoreParam(
        key: 'resistance',
        module: modulePsyche,
        label: 'Resistance',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      const LoreParam(
        key: 'affection',
        module: moduleRelationship,
        label: 'Affection',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
        hudPinned: true,
        accentHex: '#F48FB1',
      ),
      const LoreParam(
        key: 'corruption',
        module: modulePsyche,
        label: 'Corruption',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
        hudPinned: true,
        accentHex: '#9C27B0',
      ),
      const LoreParam(
        key: 'corruption_stage',
        module: modulePsyche,
        label: 'Corruption stage',
        type: LoreParamType.enumeration,
        enumOptions: [
          'innocent',
          'curious',
          'corrupted',
          'depraved',
          'broken',
          'unknown',
        ],
      ),
      const LoreParam(
        key: 'aftercare_need',
        module: modulePsyche,
        label: 'Aftercare need',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      const LoreParam(
        key: 'clothing_state',
        module: moduleClothing,
        label: 'Clothing',
        type: LoreParamType.text,
        hudPinned: true,
      ),
      const LoreParam(
        key: 'location',
        module: moduleLocation,
        label: 'Location',
        type: LoreParamType.text,
        hudPinned: true,
      ),
      const LoreParam(
        key: 'relationship_to_listener',
        module: moduleRelationship,
        label: 'Relationship to listener',
        type: LoreParamType.text,
      ),
    ];

    if (!includeExplicit) return list;

    list.addAll(const [
      // --- Body ---
      LoreParam(
        key: 'hymen',
        module: moduleBody,
        label: 'Hymen',
        type: LoreParamType.enumeration,
        enumOptions: [
          'intact',
          'partial',
          'broken',
          'absent',
          'unknown',
        ],
      ),
      LoreParam(
        key: 'hymen_status',
        module: moduleBody,
        label: 'Hymen (detail)',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'breast_sensitivity',
        module: moduleBody,
        label: 'Breast sensitivity',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      LoreParam(
        key: 'nipple_state',
        module: moduleBody,
        label: 'Nipple state',
        type: LoreParamType.enumeration,
        enumOptions: [
          'soft',
          'hard',
          'swollen',
          'clamped',
          'unknown',
        ],
      ),
      LoreParam(
        key: 'clit_sensitivity',
        module: moduleBody,
        label: 'Clit sensitivity',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      LoreParam(
        key: 'clit_state',
        module: moduleBody,
        label: 'Clit size / state',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'labia_state',
        module: moduleBody,
        label: 'Labia state',
        type: LoreParamType.enumeration,
        enumOptions: [
          'closed',
          'parted',
          'swollen',
          'flushed',
          'unknown',
        ],
      ),
      LoreParam(
        key: 'ass_tightness',
        module: moduleBody,
        label: 'Ass tightness',
        type: LoreParamType.gauge,
        value: 100,
        unit: '%',
      ),
      LoreParam(
        key: 'throat_training',
        module: moduleBody,
        label: 'Throat training',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      LoreParam(
        key: 'gape_vaginal',
        module: moduleBody,
        label: 'Gape (vaginal)',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'gape_anal',
        module: moduleBody,
        label: 'Gape (anal)',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'belly_state',
        module: moduleBody,
        label: 'Stretch marks / belly',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'body_temperature',
        module: moduleBody,
        label: 'Body temperature',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'sweat',
        module: moduleBody,
        label: 'Sweat',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      LoreParam(
        key: 'hair_state',
        module: moduleBody,
        label: 'Hair state',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'voice_moan_level',
        module: moduleBody,
        label: 'Voice / moan level',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      LoreParam(
        key: 'breathing',
        module: moduleBody,
        label: 'Breathing',
        type: LoreParamType.enumeration,
        enumOptions: [
          'calm',
          'ragged',
          'hyperventilating',
          'held',
          'unknown',
        ],
      ),
      LoreParam(
        key: 'orifice_vaginal',
        module: moduleBody,
        label: 'Vaginal state',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'orifice_anal',
        module: moduleBody,
        label: 'Anal state',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'orifice_oral',
        module: moduleBody,
        label: 'Oral state',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'marks',
        module: moduleBody,
        label: 'Marks / fluids on body',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'scent_pussy',
        module: moduleBody,
        label: 'Smell of pussy',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'cervical_position',
        module: moduleBody,
        label: 'Cervical position',
        type: LoreParamType.enumeration,
        enumOptions: [
          'high',
          'mid',
          'low',
          'soft',
          'firm',
          'open',
          'closed',
          'unknown',
        ],
      ),
      LoreParam(
        key: 'stain_thighs_sheets',
        module: moduleBody,
        label: 'Stain on thighs / sheets',
        type: LoreParamType.text,
      ),

      // --- Face ---
      LoreParam(
        key: 'face_state',
        module: moduleFace,
        label: 'Makeup / tears / drool',
        type: LoreParamType.text,
      ),

      // --- Clothing ---
      LoreParam(
        key: 'panties',
        module: moduleClothing,
        label: 'Panties',
        type: LoreParamType.text,
        hudPinned: true,
      ),
      LoreParam(
        key: 'scent_panties',
        module: moduleClothing,
        label: 'Smell of panties',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'bra_state',
        module: moduleClothing,
        label: 'Bra state',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'skirt_hiked',
        module: moduleClothing,
        label: 'Skirt / dress hiked',
        type: LoreParamType.boolean,
        value: false,
      ),
      LoreParam(
        key: 'exposure_level',
        module: moduleClothing,
        label: 'Exposure level',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      LoreParam(
        key: 'cum_on_clothes',
        module: moduleClothing,
        label: 'Cum on clothes',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'ruined_clothing',
        module: moduleClothing,
        label: 'Torn / ruined clothing',
        type: LoreParamType.text,
      ),

      // --- Toys / accessories ---
      LoreParam(
        key: 'accessories',
        module: moduleToys,
        label: 'Accessories',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'toy_in_use',
        module: moduleToys,
        label: 'Toy in use',
        type: LoreParamType.text,
      ),

      // --- Fluids ---
      LoreParam(
        key: 'womb_ml',
        module: moduleFluids,
        label: 'Womb',
        type: LoreParamType.number,
        value: 0,
        unit: 'ml',
      ),
      LoreParam(
        key: 'pussy_ml',
        module: moduleFluids,
        label: 'Pussy',
        type: LoreParamType.number,
        value: 0,
        unit: 'ml',
      ),
      LoreParam(
        key: 'pussy_juice_ml',
        module: moduleFluids,
        label: 'Pussy juice',
        type: LoreParamType.number,
        value: 0,
        unit: 'ml',
      ),
      LoreParam(
        key: 'sperm_in_pussy_ml',
        module: moduleFluids,
        label: 'Sperm in pussy',
        type: LoreParamType.number,
        value: 0,
        unit: 'ml',
      ),
      LoreParam(
        key: 'sperm_in_womb_ml',
        module: moduleFluids,
        label: 'Sperm in womb',
        type: LoreParamType.number,
        value: 0,
        unit: 'ml',
      ),
      LoreParam(
        key: 'sperm_in_womb_million',
        module: moduleFluids,
        label: 'Sperm in womb',
        type: LoreParamType.number,
        value: 0,
        unit: 'million',
      ),
      LoreParam(
        key: 'anal_cum_ml',
        module: moduleFluids,
        label: 'Anal cum',
        type: LoreParamType.number,
        value: 0,
        unit: 'ml',
      ),
      LoreParam(
        key: 'oral_cum_ml',
        module: moduleFluids,
        label: 'Oral / throat cum',
        type: LoreParamType.number,
        value: 0,
        unit: 'ml',
      ),
      LoreParam(
        key: 'creampie_freshness',
        module: moduleFluids,
        label: 'Creampie freshness',
        type: LoreParamType.enumeration,
        enumOptions: [
          'none',
          'fresh',
          'leaking',
          'dried',
          'unknown',
        ],
      ),
      LoreParam(
        key: 'squirt_count_session',
        module: moduleFluids,
        label: 'Squirt count (session)',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'squirt_count_lifetime',
        module: moduleFluids,
        label: 'Squirt count (lifetime)',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'squirt_volume_session_ml',
        module: moduleFluids,
        label: 'Squirting volume (session)',
        type: LoreParamType.number,
        value: 0,
        unit: 'ml',
      ),
      LoreParam(
        key: 'breast_milk_ml',
        module: moduleFluids,
        label: 'Breast milk',
        type: LoreParamType.number,
        value: 0,
        unit: 'ml',
      ),
      LoreParam(
        key: 'lubricant_ml',
        module: moduleFluids,
        label: 'Lubricant',
        type: LoreParamType.number,
        value: 0,
        unit: 'ml',
      ),
      LoreParam(
        key: 'lubricant_type',
        module: moduleFluids,
        label: 'Lubricant type',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'bladder_urgency',
        module: moduleFluids,
        label: 'Bladder urgency',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      LoreParam(
        key: 'bowel_urgency',
        module: moduleFluids,
        label: 'Bowel urgency',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      LoreParam(
        key: 'cervical_mucus_ml',
        module: moduleFluids,
        label: 'Cervical mucus',
        type: LoreParamType.number,
        value: 0,
        unit: 'ml',
      ),
      LoreParam(
        key: 'cum_load_ml',
        module: moduleFluids,
        label: 'Cum load',
        type: LoreParamType.number,
        value: 0,
        unit: 'ml',
      ),
      LoreParam(
        key: 'wetness',
        module: moduleFluids,
        label: 'Wetness',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
        hudPinned: true,
        accentHex: '#4FC3F7',
      ),

      // --- Fertility ---
      LoreParam(
        key: 'ovulation',
        module: moduleFertility,
        label: 'Ovulation',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'egg_quality',
        module: moduleFertility,
        label: 'Egg quality',
        type: LoreParamType.enumeration,
        enumOptions: [
          'excellent',
          'good',
          'average',
          'poor',
          'none',
          'unknown',
        ],
      ),
      LoreParam(
        key: 'fertile_window',
        module: moduleFertility,
        label: 'Fertile window',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'fertile_hours_left',
        module: moduleFertility,
        label: 'Fertile hours left',
        type: LoreParamType.number,
      ),
      LoreParam(
        key: 'menstruation_cycles',
        module: moduleFertility,
        label: 'Menstruation cycles',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'cycle_day',
        module: moduleFertility,
        label: 'Day of cycle',
        type: LoreParamType.number,
      ),
      LoreParam(
        key: 'implantation_chance',
        module: moduleFertility,
        label: 'Implantation chance',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      LoreParam(
        key: 'pregnancy_chance',
        module: moduleFertility,
        label: 'Percentage of pregnancy',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
        hudPinned: true,
        accentHex: '#EC407A',
      ),
      LoreParam(
        key: 'pregnancy_detail',
        module: moduleFertility,
        label: 'Pregnancy (detail)',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'pregnancy',
        module: moduleFertility,
        label: 'Pregnancy',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'pregnancy_weeks',
        module: moduleFertility,
        label: 'Weeks pregnant',
        type: LoreParamType.number,
      ),
      LoreParam(
        key: 'trimester',
        module: moduleFertility,
        label: 'Trimester',
        type: LoreParamType.enumeration,
        enumOptions: ['none', '1', '2', '3', 'unknown'],
      ),
      LoreParam(
        key: 'morning_sickness',
        module: moduleFertility,
        label: 'Morning sickness',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      LoreParam(
        key: 'sperm_motility',
        module: moduleFertility,
        label: 'Sperm motility (in womb)',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),
      LoreParam(
        key: 'last_creampie_ago',
        module: moduleFertility,
        label: 'Last creampie ago',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'breeding_urge',
        module: moduleFertility,
        label: 'Breeding urge',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),

      // --- Risk / contraception ---
      LoreParam(
        key: 'contraception',
        module: moduleRisk,
        label: 'Contraception',
        type: LoreParamType.enumeration,
        enumOptions: [
          'none',
          'pill',
          'condom',
          'pull_out',
          'iud',
          'other',
          'unknown',
        ],
      ),
      LoreParam(
        key: 'contraception_reliability',
        module: moduleRisk,
        label: 'Contraception reliability',
        type: LoreParamType.gauge,
        value: 0,
        unit: '%',
      ),

      // --- Kink / activity counts ---
      LoreParam(
        key: 'kinks_yes',
        module: moduleKink,
        label: 'Kinks (yes)',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'kinks_maybe',
        module: moduleKink,
        label: 'Kinks (maybe)',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'kinks_no',
        module: moduleKink,
        label: 'Kinks (no) / limits',
        type: LoreParamType.text,
      ),
      LoreParam(
        key: 'climax_count_session',
        module: moduleKink,
        label: 'Climax count (session)',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'climax_count_track',
        module: moduleKink,
        label: 'Climax count (track)',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'climax_count_lifetime',
        module: moduleKink,
        label: 'Climax count (lifetime)',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'orgasm_denied',
        module: moduleKink,
        label: 'Edging / denied orgasm',
        type: LoreParamType.boolean,
        value: false,
      ),
      LoreParam(
        key: 'orgasm_denied_count',
        module: moduleKink,
        label: 'Denied orgasm count',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'masturbation_week',
        module: moduleKink,
        label: 'Masturbation (week)',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'masturbation_lifetime',
        module: moduleKink,
        label: 'Masturbation (lifetime)',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'sex_lifetime',
        module: moduleKink,
        label: 'Sex (lifetime)',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'oral_given_lifetime',
        module: moduleKink,
        label: 'Oral given (lifetime)',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'oral_received_lifetime',
        module: moduleKink,
        label: 'Oral received (lifetime)',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'anal_sex_lifetime',
        module: moduleKink,
        label: 'Anal sex (lifetime)',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'creampie_count_lifetime',
        module: moduleKink,
        label: 'Creampie count (lifetime)',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'creampie_count_today',
        module: moduleKink,
        label: 'Creampie count (today)',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'partners_count',
        module: moduleKink,
        label: 'Partners count',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'public_play_count',
        module: moduleKink,
        label: 'Public play count',
        type: LoreParamType.number,
        value: 0,
      ),
      LoreParam(
        key: 'toy_use_lifetime',
        module: moduleKink,
        label: 'Toy use (lifetime)',
        type: LoreParamType.number,
        value: 0,
      ),
    ]);
    return list;
  }
}
